[versions]
loom = "1.1.+"
loom_quiltflower = "1.8.+"

minotaur = "2.5.+"
cursegradle = "2.+"
github_release = "2.+"
machete = "1.+"

minecraft = "1.19.4-rc1"
yarn = "1"
fabric_loader = "0.14.17"
fabric_api = "0.75.1+1.19.4"
yacl = "2.3.0+beta.3+update.1.19.4-SNAPSHOT"
mod_menu = "6.1.0-alpha.1"
mixin_extras = "0.2.0-beta.1"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }

fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api" }
yacl = { module = "dev.isxander:yet-another-config-lib", version.ref = "yacl" }
mod_menu = { module = "com.terraformersmc:modmenu", version.ref = "mod_menu" }
mixin_extras = { module = "com.github.llamalad7:mixinextras", version.ref = "mixin_extras" }

[plugins]
loom = { id = "fabric-loom", version.ref = "loom" }
loom_quiltflower = { id = "io.github.juuxel.loom-quiltflower", version.ref = "loom_quiltflower" }

minotaur = { id = "com.modrinth.minotaur", version.ref = "minotaur" }
cursegradle = { id = "me.hypherionmc.cursegradle", version.ref = "cursegradle" }
github_release = { id = "com.github.breadmoirai.github-release", version.ref = "github_release" }
machete = { id = "io.github.p03w.machete", version.ref = "machete" }
